/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlueprintsRouteImport } from './routes/blueprints'
import { Route as ContextRouteImport } from './routes/context'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GatekeepersRouteImport } from './routes/gatekeepers'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as MattersRouteImport } from './routes/matters'
import { Route as OutputsRouteImport } from './routes/outputs'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TeamRouteImport } from './routes/team'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as BlueprintIdRouteImport } from './routes/blueprint.$id'
import { Route as GadgetIdRouteImport } from './routes/gadget.$id'
import { Route as GatekeepersAppIdRouteImport } from './routes/gatekeepers_.$appId'
import { Route as MatterIdRouteImport } from './routes/matter.$id'
import { Route as PlaybooksSlugRouteImport } from './routes/playbooks.$slug'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as WorkspaceIdRouteImport } from './routes/workspace.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsRoute = BlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GatekeepersRoute = GatekeepersRouteImport.update({
  id: '/gatekeepers',
  path: '/gatekeepers',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersRoute = MattersRouteImport.update({
  id: '/matters',
  path: '/matters',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputsRoute = OutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintIdRoute = BlueprintIdRouteImport.update({
  id: '/blueprint/$id',
  path: '/blueprint/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GadgetIdRoute = GadgetIdRouteImport.update({
  id: '/gadget/$id',
  path: '/gadget/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GatekeepersAppIdRoute = GatekeepersAppIdRouteImport.update({
  id: '/gatekeepers_/$appId',
  path: '/gatekeepers/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatterIdRoute = MatterIdRouteImport.update({
  id: '/matter/$id',
  path: '/matter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksSlugRoute = PlaybooksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlaybooksRoute,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blueprints': typeof BlueprintsRoute
  '/context': typeof ContextRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/inbox': typeof InboxRoute
  '/matters': typeof MattersRoute
  '/outputs': typeof OutputsRoute
  '/playbooks': typeof PlaybooksRouteWithChildren
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers/$appId': typeof GatekeepersAppIdRoute
  '/matter/$id': typeof MatterIdRoute
  '/playbooks/$slug': typeof PlaybooksSlugRoute
  '/portal/$token': typeof PortalTokenRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blueprints': typeof BlueprintsRoute
  '/context': typeof ContextRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/inbox': typeof InboxRoute
  '/matters': typeof MattersRoute
  '/outputs': typeof OutputsRoute
  '/playbooks': typeof PlaybooksRouteWithChildren
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers/$appId': typeof GatekeepersAppIdRoute
  '/matter/$id': typeof MatterIdRoute
  '/playbooks/$slug': typeof PlaybooksSlugRoute
  '/portal/$token': typeof PortalTokenRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blueprints': typeof BlueprintsRoute
  '/context': typeof ContextRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/inbox': typeof InboxRoute
  '/matters': typeof MattersRoute
  '/outputs': typeof OutputsRoute
  '/playbooks': typeof PlaybooksRouteWithChildren
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers_/$appId': typeof GatekeepersAppIdRoute
  '/matter/$id': typeof MatterIdRoute
  '/playbooks/$slug': typeof PlaybooksSlugRoute
  '/portal/$token': typeof PortalTokenRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blueprints'
    | '/context'
    | '/explore'
    | '/gatekeepers'
    | '/inbox'
    | '/matters'
    | '/outputs'
    | '/playbooks'
    | '/profile'
    | '/providers'
    | '/search'
    | '/signup'
    | '/team'
    | '/workspaces'
    | '/blueprint/$id'
    | '/gadget/$id'
    | '/gatekeepers/$appId'
    | '/matter/$id'
    | '/playbooks/$slug'
    | '/portal/$token'
    | '/workspace/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blueprints'
    | '/context'
    | '/explore'
    | '/gatekeepers'
    | '/inbox'
    | '/matters'
    | '/outputs'
    | '/playbooks'
    | '/profile'
    | '/providers'
    | '/search'
    | '/signup'
    | '/team'
    | '/workspaces'
    | '/blueprint/$id'
    | '/gadget/$id'
    | '/gatekeepers/$appId'
    | '/matter/$id'
    | '/playbooks/$slug'
    | '/portal/$token'
    | '/workspace/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blueprints'
    | '/context'
    | '/explore'
    | '/gatekeepers'
    | '/inbox'
    | '/matters'
    | '/outputs'
    | '/playbooks'
    | '/profile'
    | '/providers'
    | '/search'
    | '/signup'
    | '/team'
    | '/workspaces'
    | '/blueprint/$id'
    | '/gadget/$id'
    | '/gatekeepers_/$appId'
    | '/matter/$id'
    | '/playbooks/$slug'
    | '/portal/$token'
    | '/workspace/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlueprintsRoute: typeof BlueprintsRoute
  ContextRoute: typeof ContextRoute
  ExploreRoute: typeof ExploreRoute
  GatekeepersRoute: typeof GatekeepersRoute
  InboxRoute: typeof InboxRoute
  MattersRoute: typeof MattersRoute
  OutputsRoute: typeof OutputsRoute
  PlaybooksRoute: typeof PlaybooksRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ProvidersRoute: typeof ProvidersRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  TeamRoute: typeof TeamRoute
  WorkspacesRoute: typeof WorkspacesRoute
  BlueprintIdRoute: typeof BlueprintIdRoute
  GadgetIdRoute: typeof GadgetIdRoute
  GatekeepersAppIdRoute: typeof GatekeepersAppIdRoute
  MatterIdRoute: typeof MatterIdRoute
  PortalTokenRoute: typeof PortalTokenRoute
  WorkspaceIdRoute: typeof WorkspaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints': {
      id: '/blueprints'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof BlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatekeepers': {
      id: '/gatekeepers'
      path: '/gatekeepers'
      fullPath: '/gatekeepers'
      preLoaderRoute: typeof GatekeepersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters': {
      id: '/matters'
      path: '/matters'
      fullPath: '/matters'
      preLoaderRoute: typeof MattersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outputs': {
      id: '/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof OutputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint/$id': {
      id: '/blueprint/$id'
      path: '/blueprint/$id'
      fullPath: '/blueprint/$id'
      preLoaderRoute: typeof BlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gadget/$id': {
      id: '/gadget/$id'
      path: '/gadget/$id'
      fullPath: '/gadget/$id'
      preLoaderRoute: typeof GadgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatekeepers_/$appId': {
      id: '/gatekeepers_/$appId'
      path: '/gatekeepers/$appId'
      fullPath: '/gatekeepers/$appId'
      preLoaderRoute: typeof GatekeepersAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matter/$id': {
      id: '/matter/$id'
      path: '/matter/$id'
      fullPath: '/matter/$id'
      preLoaderRoute: typeof MatterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks/$slug': {
      id: '/playbooks/$slug'
      path: '/$slug'
      fullPath: '/playbooks/$slug'
      preLoaderRoute: typeof PlaybooksSlugRouteImport
      parentRoute: typeof PlaybooksRoute
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id': {
      id: '/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlaybooksRouteChildren {
  PlaybooksSlugRoute: typeof PlaybooksSlugRoute
}

const PlaybooksRouteChildren: PlaybooksRouteChildren = {
  PlaybooksSlugRoute: PlaybooksSlugRoute,
}

const PlaybooksRouteWithChildren = PlaybooksRoute._addFileChildren(
  PlaybooksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlueprintsRoute: BlueprintsRoute,
  ContextRoute: ContextRoute,
  ExploreRoute: ExploreRoute,
  GatekeepersRoute: GatekeepersRoute,
  InboxRoute: InboxRoute,
  MattersRoute: MattersRoute,
  OutputsRoute: OutputsRoute,
  PlaybooksRoute: PlaybooksRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ProvidersRoute: ProvidersRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  TeamRoute: TeamRoute,
  WorkspacesRoute: WorkspacesRoute,
  BlueprintIdRoute: BlueprintIdRoute,
  GadgetIdRoute: GadgetIdRoute,
  GatekeepersAppIdRoute: GatekeepersAppIdRoute,
  MatterIdRoute: MatterIdRoute,
  PortalTokenRoute: PortalTokenRoute,
  WorkspaceIdRoute: WorkspaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
